version: 0.2

phases:
  install: 
    runtime-versions:
      php: 8.0
  pre_build: # commands to be run before build
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    # login to Elastic container registry
    - eval $(aws ecr get-login-password --region us-west-2 --no-include-email | sed 's|https://||')
    - REPOSITORY_URI=470491217479.dkr.ecr.us-west-2.amazonaws.com/reviewanything
    - IMAGE_TAG=1.0
  build:
    commands:
    - echo Build started on `date`
    - apt-get install software-properties-common
    - add-apt-repository ppa:ondrej/php
    - apt-get update
    - apt-get install php8.1 -y
    - php -v
    - apt-get install libapache2-mod-php8.1 php8.1-fpm libapache2-mod-fcgid php8.1-curl php8.1-dev php8.1-gd php8.1-mbstring php8.1-zip php8.1-mysql php8.1-xml
    - ln -s /usr/bin/php8 /usr/bin/php
    - echo installing composer..
    - composer install
    - echo creating .env file..
    - cp .env.example .env
    - echo generating app key
    - php artisan key:generate
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push $REPOSITORY_URI:$IMAGE_TAG
